### ISSUE TITLE
Could you provide some references，please?

### ISSUE THREAD

**Issue by liumeijiang** [MagicMumble/ChromaticAberrationCorrection#1]

**Comment by MagicMumble** [comment]
Sure. These articles were extremely helpful.
[10.1007978-3-642-53842-1_2.pdf](https://github.com/MagicMumble/ChromaticAberrationCorrection/files/6310636/10.1007978-3-642-53842-1_2.pdf)
[Removing.chromatic.aberration.by.digital.image.processing.pdf](https://github.com/MagicMumble/ChromaticAberrationCorrection/files/6310656/Removing.chromatic.aberration.by.digital.image.processing.pdf)
